version: "3.3"

services:

  db:
    build:
      context: .
      dockerfile: ./dockerfile/postgresql/Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
      - .init.sql:/docker-entrypoint-initdb/10-init.sql
    restart: on-failure:10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - ./environment/production/project.env

  django:
    build:
      context: .
      dockerfile: ./dockerfile/django/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - .:/code/
    env_file:
      - ./environment/production/project.env
    command: daphne -b 0.0.0.0 -p 8005 project.asgi:application

  nginx:
    image: nginx
    volumes:
      - "./confs-docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./confs-docker/nginx/django.conf:/etc/nginx/conf.d/django.conf"
      - ./static:/static
    ports:
      - "80:80"
    command: nginx -g "daemon off;"
    restart: on-failure

volumes:
  db-data:


